version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-updates:
        patterns:
          - '*'
  - package-ecosystem: 'npm'
    directory: '/page'
    schedule:
      interval: 'weekly'
    groups:
      all-updates:
        patterns:
          - '*'
